
fuseki:
  image: ghcr.io/lock-unlock-testdata/fuseki
  # image: lock-unlock-testdata/fuseki
  tag: 4.10.0
  
  dataset:
    file_url: https://raw.githubusercontent.com/kadaster-labs/lock-unlock-testdata/main/testdata-brk/lock-unlock-brk.ttl.gz

ingress:
  host: tbd
  # host: fuseki.127.0.0.1.nip.io